# Generated by Django 5.2.1 on 2026-03-18 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('avatar_initial', models.CharField(default='M', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('theme', 'Theme'), ('quick', 'Quick'), ('adventure', 'Adventure'), ('daily', 'Daily')], max_length=24)),
                ('theme', models.CharField(blank=True, max_length=120)),
                ('level', models.CharField(blank=True, max_length=60)),
                ('lang', models.CharField(default='fr', max_length=10)),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_answers', models.PositiveIntegerField()),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('score_points', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.playerprofile')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
