name: Feature request
description: Suggest an improvement
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user problem are you solving?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your idea.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope and impact
      description: What areas are affected?
